"""
==========================================================
Utility Functions for AI Agents Bootcamp
==========================================================
Shared helpers used across all days.
"""

import os
from datetime import datetime
from typing import Optional


def ensure_output_dir(dir_name: str = "outputs") -> str:
    """Create output directory if it doesn't exist."""
    os.makedirs(dir_name, exist_ok=True)
    return dir_name


def generate_filename(base_name: str, extension: str = "md") -> str:
    """Generate a timestamped filename."""
    slug = base_name.lower().replace(" ", "_").replace(".", "")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{slug}_{timestamp}.{extension}"


def save_markdown_report(
    content: str,
    title: str,
    output_dir: str = "outputs",
    filename: Optional[str] = None
) -> str:
    """
    Save content as a markdown report.
    
    Args:
        content: The main content to save
        title: Report title
        output_dir: Directory to save to
        filename: Optional custom filename
        
    Returns:
        Path to saved file
    """
    ensure_output_dir(output_dir)
    
    if not filename:
        filename = generate_filename(title, "md")
    
    filepath = os.path.join(output_dir, filename)
    
    report = f"""# {title}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

{content}

---

*Generated by AI Agents Bootcamp | [Standout Systems](https://teodoracoach.substack.com/)*
"""
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)
    
    return filepath


def print_header(text: str, width: int = 60):
    """Print a formatted header."""
    print("\n" + "=" * width)
    print(f"  {text}")
    print("=" * width + "\n")


def print_step(step_num: int, total: int, message: str):
    """Print a step indicator."""
    print(f"{'📊' if step_num == 1 else '✅' if step_num == total else '⚙️'} Step {step_num}/{total}: {message}")


def validate_api_key(key_name: str = "OPENAI_API_KEY") -> bool:
    """Check if API key is set."""
    key = os.getenv(key_name)
    if not key:
        print(f"❌ Error: {key_name} not found!")
        print(f"   Please set it in your .env file or environment.")
        return False
    return True


class AgentMemory:
    """
    Simple memory class for agents.
    
    Provides short-term (current task) and long-term (history) storage.
    """
    
    def __init__(self):
        self.short_term = {}
        self.long_term = []
        self.metadata = {
            "created": datetime.now().isoformat(),
            "task_count": 0
        }
    
    def store(self, key: str, value: any):
        """Store in short-term memory."""
        self.short_term[key] = value
    
    def retrieve(self, key: str, default: any = None) -> any:
        """Retrieve from short-term memory."""
        return self.short_term.get(key, default)
    
    def commit(self):
        """Move short-term memory to long-term history."""
        if self.short_term:
            entry = {
                "timestamp": datetime.now().isoformat(),
                "data": self.short_term.copy()
            }
            self.long_term.append(entry)
            self.metadata["task_count"] += 1
            self.short_term = {}
    
    def get_history(self, n: int = None) -> list:
        """Get last n entries from history."""
        if n:
            return self.long_term[-n:]
        return self.long_term
    
    def clear(self):
        """Clear all memory."""
        self.short_term = {}
        self.long_term = []
        self.metadata["task_count"] = 0
